### ISSUE TITLE
Question about useDebouncedCallback with concurrent mode

### ISSUE THREAD

**Issue by johnywith1n** [xnimorz/use-debounce#190]
Given that the latest function is used thanks to the [side effect here](https://github.com/xnimorz/use-debounce/blob/master/src/useDebouncedCallback.ts#L127), are there any caveats about using `useDebouncedCallback` with concurrent mode enabled?

Or in other words, is it hypothetically possible to use the "wrong" callback because the function ref is being set outside of a `useEffect`

**Comment by xnimorz** [comment]
Setting ref outside `useEffect` is well-known practice. 

As matter of fact, if we put ref assignment inside useEffect it leads to incorrect function execution, as components in react can be un-mounted, re-mounted. And the easiest repro will be to turn on strict mode. 

So, moving ref assignment outside `useEffect` was intentional, to ensure the correctness of the hook.
